package com.jwindustries.isitvegan;

import android.content.Context;

import java.util.Arrays;
import java.util.List;

public class IngredientList {
    public static List<Ingredient> getIngredientList(Context context) {
        List<Ingredient> ingredientList = Arrays.asList(
                new Ingredient("(Di)kaliuminosinaat", "Potassium inosinate", IngredientType.VEGAN, "E632"),
                new Ingredient("(Di)natrium-5'-ribonucleotiden", "Disodium 5'-ribonucleotides", IngredientType.VEGAN, "E635"),
                new Ingredient("(Di)natriuminosinaat", "Disodium inosinate", IngredientType.VEGAN, "E631"),
                new Ingredient("Agar, agaragar", "Agar, agar-agar", IngredientType.VEGAN, "E406"),
                new Ingredient("Angorawol", "Angora wool", IngredientType.NOT_VEGAN, null),
                new Ingredient("Arabische gom", "Gum arabic", IngredientType.VEGAN, "E414"),
                new Ingredient("Ascorbaat", "Ascorbate", IngredientType.VEGAN, null),
                new Ingredient("Ascorbinezuur, vitamine C", "Ascorbic acid, vitamin C", IngredientType.VEGAN, "E300"),
                new Ingredient("Ascorbylpalmitaat", "Ascorbyl palmitate", IngredientType.VEGAN, "E304"),
                new Ingredient("Astaxanthine", "Astaxanthin", IngredientType.VEGAN, "E161j"),
                new Ingredient("Aubergine", "Eggplant", IngredientType.VEGAN, null),
                new Ingredient("Beenderkool", "Bone char", IngredientType.NOT_VEGAN, null),
                new Ingredient("Bijenwas", "Beeswax", IngredientType.NOT_VEGAN, "E901"),
                new Ingredient("Botervet", "Butter fat", IngredientType.NOT_VEGAN, null),
                new Ingredient("Cacaoboter", "Cocoa butter, cacao butter", IngredientType.VEGAN, null),
                new Ingredient("Cacaomassa", "Cocoa mass", IngredientType.VEGAN, null),
                new Ingredient("Calcium-5'-ribonucleotiden", "Calcium 5'-ribonucleotides", IngredientType.VEGAN, "E634"),
                new Ingredient("Calciumascorbaat", "Calcium ascorbate", IngredientType.VEGAN, "E302"),
                new Ingredient("Calciumformiaat", "Calcium formate", IngredientType.VEGAN, "E238"),
                new Ingredient("Calciumguanylaat", "Calcium guanylate", IngredientType.VEGAN, "E629"),
                new Ingredient("Calciuminosinaat", "Calcium inosinate", IngredientType.VEGAN, "E633"),
                new Ingredient("Calciumlactaat", "Calcium lactate", IngredientType.VEGAN, "E327"),
                new Ingredient("Caseïne, caseïnaat", "Casein, caseinate", IngredientType.NOT_VEGAN, null),
                new Ingredient("Castoreum, bevergeil", "Castoreum", IngredientType.NOT_VEGAN, null),
                new Ingredient("Cera alba", "Cera alba", IngredientType.NOT_VEGAN, "E901"),
                new Ingredient("Cera flava", "Cera flava", IngredientType.NOT_VEGAN, "E901"),
                new Ingredient("Cholinezuur", "Cholic acid", IngredientType.NOT_VEGAN, "E1000"),
                new Ingredient("Citranaxanthine", "Citranaxanthin", IngredientType.VEGAN, "E161i"),
                new Ingredient("Collageen ", "Collagen", IngredientType.NOT_VEGAN, null),
                new Ingredient("Ei", "Egg", IngredientType.NOT_VEGAN, null),
                new Ingredient("Eigeel", "Egg yolk", IngredientType.NOT_VEGAN, null),
                new Ingredient("Foelie", "Mace", IngredientType.VEGAN, null),
                new Ingredient("Gekarameliseerde suikerstroop", "Caramelized sugar syrup", IngredientType.VEGAN, null),
                new Ingredient("Gelatine", "Gelatin", IngredientType.NOT_VEGAN, "E441, E485"),
                new Ingredient("Glutamaat", "Monosodium glutamate", IngredientType.VEGAN, "E621"),
                new Ingredient("Glycerol, glycerine", "Glycerol, glycerine", IngredientType.VEGAN, "E422"),
                new Ingredient("Guanosinemonofosfaat, GMP", "Guanosine monophosphate, GMP", IngredientType.VEGAN, "E626"),
                new Ingredient("Guanylzuur", "Guanylic acid", IngredientType.VEGAN, "E626"),
                new Ingredient("Hennep", "Hemp", IngredientType.VEGAN, null),
                new Ingredient("Honing", "Honey", IngredientType.NOT_VEGAN, null),
                new Ingredient("Inosinemonofosfaat, IMP", "Inosine monophosphate, IMP", IngredientType.VEGAN, "E630"),
                new Ingredient("Inosinezuur", "Inosinic acid", IngredientType.VEGAN, "E630"),
                new Ingredient("Kaliumascorbaat", "Potassium ascorbate", IngredientType.VEGAN, null),
                new Ingredient("Kaliumguanylaat", "Potassium guanylate", IngredientType.VEGAN, "E628"),
                new Ingredient("Kaliumlactaat", "Potassium lactate", IngredientType.VEGAN, "E326"),
                new Ingredient("Kaliumnitraat, (kali)salpeter", "Potassium nitrate, saltpetre", IngredientType.VEGAN, "E252"),
                new Ingredient("Karmijnzuur, cochenille-extract", "Carmine, cochineal", IngredientType.NOT_VEGAN, "E120"),
                new Ingredient("Karnemelk", "Buttermilk", IngredientType.NOT_VEGAN, null),
                new Ingredient("Kasjmier", "Cashmere", IngredientType.NOT_VEGAN, null),
                new Ingredient("Katoen", "Cotton", IngredientType.VEGAN, null),
                new Ingredient("Keratine", "Keratin", IngredientType.NOT_VEGAN, null),
                new Ingredient("Kokosvezel", "Coconut fiber", IngredientType.VEGAN, null),
                new Ingredient("Kurkuma", "Turmeric", IngredientType.VEGAN, null),
                new Ingredient("L-Cysteïne", "L-Cysteine", IngredientType.DEPENDS, "E920"),
                new Ingredient("L-Cystine", "L-Cystine", IngredientType.DEPENDS, "E921"),
                new Ingredient("Lactitol", "Lactitol", IngredientType.NOT_VEGAN, "E966"),
                new Ingredient("Lactobacillus", "Lactobacillus", IngredientType.DEPENDS, null),
                new Ingredient("Lactose, melksuiker", "Lactose", IngredientType.NOT_VEGAN, null),
                new Ingredient("Latex", "Latex", IngredientType.VEGAN, null),
                new Ingredient("Lavaswortel", "Lovage root", IngredientType.VEGAN, null),
                new Ingredient("Lecithine, lecithinen", "Lecithin, lecithins", IngredientType.DEPENDS, "E322"),
                new Ingredient("Linnen", "Linen", IngredientType.VEGAN, null),
                new Ingredient("Lyocell", "Lyocell", IngredientType.VEGAN, null),
                new Ingredient("Lysozym, muramidase", "Lysozyme, muramidase", IngredientType.NOT_VEGAN, "E1105"),
                new Ingredient("Maltodextrine", "Maltodextrin", IngredientType.VEGAN),
                new Ingredient("Melk", "Milk", IngredientType.DEPENDS, null),
                new Ingredient("Melkpoeder", "Powdered milk, dried milk", IngredientType.NOT_VEGAN, null),
                new Ingredient("Melkzuur", "Lactic acid", IngredientType.VEGAN, "E270"),
                new Ingredient("Mierenzuur, metaanzuur", "Formic acid, methanoic acid", IngredientType.VEGAN, "E236"),
                new Ingredient("Modal", "Modal", IngredientType.VEGAN, null),
                new Ingredient("Mono- en diglyceriden", "Mono- and diglycerides of fatty acids", IngredientType.VEGAN, "E471"),
                new Ingredient("Muskus", "Musk", IngredientType.NOT_VEGAN, null),
                new Ingredient("Natriumascorbaat", "Sodium ascorbate", IngredientType.VEGAN, "E301"),
                new Ingredient("Natriumformiaat", "Sodium formate", IngredientType.VEGAN, "E237"),
                new Ingredient("Natriumguanylaat", "Disodium guanylate", IngredientType.VEGAN, "E627"),
                new Ingredient("Natriumlactaat", "Sodium lactate", IngredientType.VEGAN, "E325"),
                new Ingredient("Natriumnitriet", "Sodium nitrite", IngredientType.VEGAN, "E250"),
                new Ingredient("Nisine", "Nisin", IngredientType.DEPENDS, "E234"),
                new Ingredient("Palmvet", "Palm fat", IngredientType.VEGAN),
                new Ingredient("Parels", "Pearls", IngredientType.NOT_VEGAN, null),
                new Ingredient("Peterselie", "Parsley", IngredientType.VEGAN, null),
                new Ingredient("Reuzel, smout", "Lard", IngredientType.NOT_VEGAN, null),
                new Ingredient("Rundervet", "Beef fat", IngredientType.NOT_VEGAN, null),
                new Ingredient("Rundvleesextract", "Beef extract", IngredientType.NOT_VEGAN, null),
                new Ingredient("Schellak", "Schellac", IngredientType.NOT_VEGAN, "E904"),
                new Ingredient("Selderijzaad", "Celery seed", IngredientType.VEGAN, null),
                new Ingredient("Skatool, scatool", "Skatole", IngredientType.NOT_VEGAN, null),
                new Ingredient("Sojabonen", "Soybeans", IngredientType.VEGAN, null),
                new Ingredient("Sojalecithine", "Soy lecithin", IngredientType.VEGAN, "E322"),
                new Ingredient("Suiker", "Sugar", IngredientType.VEGAN, null),
                new Ingredient("Talg", "Tallow", IngredientType.NOT_VEGAN, null),
                new Ingredient("Vanille", "Vanilla", IngredientType.VEGAN, null),
                new Ingredient("Violoxanthine", "Violoxanthin", IngredientType.VEGAN, "E161e"),
                new Ingredient("Vitamine B12, cobalamine", "Vitamin B12, cobalamin", IngredientType.VEGAN, null),
                new Ingredient("Vitamine D2, ergocalciferol", "Vitamin D2, ergocalciferol", IngredientType.VEGAN, null),
                new Ingredient("Vitamine D3, cholecalciferol", "Vitamin D3, cholecalciferol", IngredientType.DEPENDS, null),
                new Ingredient("Wei-eiwit", "Whey protein", IngredientType.NOT_VEGAN, null),
                new Ingredient("Wei, melkwei, melkserum, lactoserum", "Whey", IngredientType.NOT_VEGAN, null),
                new Ingredient("Weipoeder", "Whey powder", IngredientType.NOT_VEGAN, null),
                new Ingredient("Wol", "Wool", IngredientType.NOT_VEGAN, null),
                new Ingredient("Wolvet, lanoline", "Wool fat, lanolin", IngredientType.NOT_VEGAN, "E913"),
                new Ingredient("Wortel", "Carrot", IngredientType.VEGAN, null),
                new Ingredient("Zeaxanthine", "Zeaxanthin", IngredientType.VEGAN, "E161h"),
                new Ingredient("Zeewier", "Seaweed", IngredientType.VEGAN, null),
                new Ingredient("Zijde", "Silk", IngredientType.NOT_VEGAN, null),
                new Ingredient("Zonnebloemlecithine", "Sunflower lecithin", IngredientType.VEGAN, "E322"),
                new Ingredient("Zout", "Salt", IngredientType.VEGAN, null)
        );

        // Sort alphabetically, ignoring '(' characters
        String locale = Utils.getIngredientLocale(context);
        ingredientList.sort((a, b) -> a.getName(locale).replace("(", "").compareTo(b.getName(locale).replace("(", "")));

        return ingredientList;
    }
}
